---
apiVersion: v1
kind: Service
metadata:
  name: product-api-db
  labels:
    app: product-api-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: product-api-db
